[package]
name = "msglint"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
clap_derive = "4.5.40"
colored = "3.0.0"
lazy_static = "1.5.0"
regex = "1.11.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
